# This file was inspired from https://github.com/google/fruit

#
# General config
#
branches:
  only:
  - master
dist: trusty
language: cpp

# Enable caching
cache:
  timeout: 600
  directories:
  - build
  - travis/mtime_cache

# Enable docker support
services:
- docker
sudo: required

#
# Configurations
#
jobs:
  include:

    ###
    # Stage: Build (1st run)
    ###

    # osx
    - stage: Build (1st run)
      os: osx
      compiler: clang
      env: CONFIG=DefaultDebug COMPILER=clang-4.0 STL=libc++
      install:
        travis/install_osx.sh
      script:
        travis/build.sh Build1
    - stage: Build (1st run)
      os: osx
      compiler: clang
      env: CONFIG=DefaultRelease COMPILER=clang-4.0 STL=libc++
      install:
        travis/install_osx.sh
      script:
        travis/build.sh Build1
    # ubuntu-16.10
    - stage: Build (1st run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultDebug LINUX=ubuntu-16.10 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build1
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (1st run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultRelease LINUX=ubuntu-16.10 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build1
      before_cache:
        docker cp storm:/storm/. .
    # debian-9
    - stage: Build (1st run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultDebug LINUX=debian-9 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build1
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (1st run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultRelease LINUX=debian-9 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build1
      before_cache:
        docker cp storm:/storm/. .

    ###
    # Stage: Build (2nd run)
    ###

    # osx
    - stage: Build (2nd run)
      os: osx
      compiler: clang
      env: CONFIG=DefaultDebug COMPILER=clang-4.0 STL=libc++
      install:
        travis/install_osx.sh
      script:
        travis/build.sh Build2
    - stage: Build (2nd run)
      os: osx
      compiler: clang
      env: CONFIG=DefaultRelease COMPILER=clang-4.0 STL=libc++
      install:
        travis/install_osx.sh
      script:
        travis/build.sh Build2
    # ubuntu-16.10
    - stage: Build (2nd run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultDebug LINUX=ubuntu-16.10 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build2
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (2nd run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultRelease LINUX=ubuntu-16.10 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build2
      before_cache:
        docker cp storm:/storm/. .
    # debian-9
    - stage: Build (2nd run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultDebug LINUX=debian-9 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build2
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (2nd run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultRelease LINUX=debian-9 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build2
      before_cache:
        docker cp storm:/storm/. .

    ###
    # Stage: Build (3rd run)
    ###

    # osx
    - stage: Build (3rd run)
      os: osx
      compiler: clang
      env: CONFIG=DefaultDebug COMPILER=clang-4.0 STL=libc++
      install:
        travis/install_osx.sh
      script:
        travis/build.sh Build3
    - stage: Build (3rd run)
      os: osx
      compiler: clang
      env: CONFIG=DefaultRelease COMPILER=clang-4.0 STL=libc++
      install:
        travis/install_osx.sh
      script:
        travis/build.sh Build3
    # ubuntu-16.10
    - stage: Build (3rd run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultDebug LINUX=ubuntu-16.10 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build3
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (3rd run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultRelease LINUX=ubuntu-16.10 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build3
      before_cache:
        docker cp storm:/storm/. .
    # debian-9
    - stage: Build (3rd run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultDebug LINUX=debian-9 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build3
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (3rd run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultRelease LINUX=debian-9 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build3
      before_cache:
        docker cp storm:/storm/. .

    ###
    # Stage: Build (4th run)
    ###

    # osx
    - stage: Build (4th run)
      os: osx
      compiler: clang
      env: CONFIG=DefaultDebug COMPILER=clang-4.0 STL=libc++
      install:
        travis/install_osx.sh
      script:
        travis/build.sh Build4
    - stage: Build (4th run)
      os: osx
      compiler: clang
      env: CONFIG=DefaultRelease COMPILER=clang-4.0 STL=libc++
      install:
        travis/install_osx.sh
      script:
        travis/build.sh Build4
    # ubuntu-16.10
    - stage: Build (4th run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultDebug LINUX=ubuntu-16.10 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build4
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (4th run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultRelease LINUX=ubuntu-16.10 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build4
      before_cache:
        docker cp storm:/storm/. .
    # debian-9
    - stage: Build (4th run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultDebug LINUX=debian-9 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build4
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (4th run)
      os: linux
      compiler: gcc
      env: CONFIG=DefaultRelease LINUX=debian-9 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh Build4
      before_cache:
        docker cp storm:/storm/. .

    ###
    # Stage: Test all
    ###

    # osx
    - stage: Test all
      os: osx
      compiler: clang
      env: CONFIG=DefaultDebug COMPILER=clang-4.0 STL=libc++
      install:
        travis/install_osx.sh
      script:
        travis/build.sh TestAll
    - stage: Test all
      os: osx
      compiler: clang
      env: CONFIG=DefaultRelease COMPILER=clang-4.0 STL=libc++
      install:
        travis/install_osx.sh
      script:
        travis/build.sh TestAll
    # ubuntu-16.10
    - stage: Test all
      os: linux
      compiler: gcc
      env: CONFIG=DefaultDebug LINUX=ubuntu-16.10 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh TestAll
      before_cache:
        docker cp storm:/storm/. .
    - stage: Test all
      os: linux
      compiler: gcc
      env: CONFIG=DefaultRelease LINUX=ubuntu-16.10 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh TestAll
      before_cache:
        docker cp storm:/storm/. .
    # debian-9
    - stage: Test all
      os: linux
      compiler: gcc
      env: CONFIG=DefaultDebug LINUX=debian-9 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh TestAll
      before_cache:
        docker cp storm:/storm/. .
    - stage: Test all
      os: linux
      compiler: gcc
      env: CONFIG=DefaultRelease LINUX=debian-9 COMPILER=gcc-6
      install:
        travis/install_linux.sh
      script:
        travis/build.sh TestAll
      before_cache:
        docker cp storm:/storm/. .

