#
# This file was inspired from https://github.com/google/fruit
#
branches:
  only:
  - master
dist: trusty
language: cpp

matrix:
  fast_finish: true

  include:

  ###
  # Ubuntu 16.10
  ###
  - compiler: gcc
    env: TEST=DefaultDebug COMPILER=gcc-6 LINUX=ubuntu-16.10
    install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
      travis/install_linux.sh
    os: linux
    script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
      travis/postsubmit.sh DefaultDebug
    before_cache:
      docker cp storm:/storm/. .
  - compiler: gcc
    env: TEST=DefaultRelease COMPILER=gcc-6 LINUX=ubuntu-16.10
    install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
      travis/install_linux.sh
    os: linux
    script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
      travis/postsubmit.sh DefaultRelease
    before_cache:
      docker cp storm:/storm/. .

  ###
  # Debian 9
  ###
  - compiler: gcc
    env: TEST=DefaultDebug COMPILER=gcc-6 LINUX=debian-9
    install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
      travis/install_linux.sh
    os: linux
    script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
      travis/postsubmit.sh DefaultDebug
    before_cache:
      docker cp storm:/storm/. .
  - compiler: gcc
    env: TEST=DefaultRelease COMPILER=gcc-6 LINUX=debian-9
    install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
      travis/install_linux.sh
    os: linux
    script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
      travis/postsubmit.sh DefaultRelease
    before_cache:
      docker cp storm:/storm/. .

  ###
  # Mac OS X
  ###
  - compiler: clang
    env: TEST=DefaultDebug COMPILER=clang-4.0 STL=libc++
    install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
      travis/install_osx.sh
    os: osx
    osx_image: xcode8
    script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
      travis/postsubmit.sh DefaultDebug
  - compiler: clang
    env: TEST=DefaultRelease COMPILER=clang-4.0 STL=libc++
    install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
      travis/install_osx.sh
    os: osx
    osx_image: xcode8
    script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
      travis/postsubmit.sh DefaultRelease

# Enable caching
cache:
  timeout: 600
  directories:
  - build
  - travis/mtime_cache

# Enable docker support
services:
- docker
sudo: required
