#
# This file was inspired from https://github.com/google/fruit
#
branches:
  only:
  - master
dist: trusty
language: cpp

matrix:
  fast_finish: true

  include:
  - compiler: gcc
    env: COMPILER=gcc-6 LINUX=ubuntu-16.10 TEST=DebugPlain
    install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
      travis/install_linux.sh
    os: linux
    script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
      timeout 2400 travis/postsubmit.sh DebugPlain
#  - compiler: gcc
#    env: COMPILER=gcc-6 UBUNTU=17.04 TEST=DebugPlain
#    install: export OS=linux; export COMPILER='gcc-6'; export UBUNTU='17.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-6'; export UBUNTU='17.04'; extras/scripts/postsubmit.sh
#      DebugPlain
#  - compiler: gcc
#    env: COMPILER=gcc-6 UBUNTU=17.04 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='gcc-6'; export UBUNTU='17.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-6'; export UBUNTU='17.04'; extras/scripts/postsubmit.sh
#      ReleasePlain
#  - compiler: clang
#    env: COMPILER=clang-4.0 STL=libstdc++ UBUNTU=17.04 TEST=DebugPlain
#    install: export OS=linux; export COMPILER='clang-4.0'; export STL='libstdc++';
#      export UBUNTU='17.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-4.0'; export STL='libstdc++';
#      export UBUNTU='17.04'; extras/scripts/postsubmit.sh DebugPlain
#  - compiler: clang
#    env: COMPILER=clang-4.0 STL=libstdc++ UBUNTU=17.04 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='clang-4.0'; export STL='libstdc++';
#      export UBUNTU='17.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-4.0'; export STL='libstdc++';
#      export UBUNTU='17.04'; extras/scripts/postsubmit.sh ReleasePlain
#  - compiler: gcc
#    env: COMPILER=gcc-6 TEST=DebugPlain
#    install: export OS=osx; export COMPILER='gcc-6'; export INSTALL_VALGRIND=1; extras/scripts/travis_ci_install_osx.sh
#    os: osx
#    osx_image: xcode8
#    script: export OS=osx; export COMPILER='gcc-6'; export INSTALL_VALGRIND=1; extras/scripts/postsubmit.sh
#      DebugPlain
  - compiler: clang
    env: COMPILER=clang-4.0 STL=libc++ TEST=DebugPlain
    install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
      travis/install_osx.sh
    os: osx
    osx_image: xcode8
    script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
      gtimeout 2400 travis/postsubmit.sh DebugPlain
#  - compiler: clang
#    env: COMPILER=clang-default STL=libc++ TEST=DebugPlain
#    install: export OS=osx; export COMPILER='clang-default'; export STL='libc++';
#      extras/scripts/travis_ci_install_osx.sh
#    os: osx
#    osx_image: xcode8.2
#    script: export OS=osx; export COMPILER='clang-default'; export STL='libc++'; extras/scripts/postsubmit.sh
#      DebugPlain

cache:
  directories:
  - build
  - travis/mtime_cache

services:
- docker
sudo: required
