# This file was inspired from https://github.com/google/fruit

#
# General config
#
branches:
  only:
  - master
dist: trusty
language: cpp

# Enable caching
cache:
  timeout: 600
  directories:
  - build
  - travis/mtime_cache

# Enable docker support
services:
- docker
sudo: required

#
# Configurations
#
jobs:
  include:

    ###
    # Stage: Build (1st run)
    ###

    # osx
    - stage: Build (1st run)
      os: osx
      compiler: clang
      env: BUILD=DefaultDebug COMPILER=clang-4.0 STL=libc++
      install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/build.sh DefaultDebug Build1
    - stage: Build (1st run)
      os: osx
      compiler: clang
      env: BUILD=DefaultRelease COMPILER=clang-4.0 STL=libc++
      install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/build.sh DefaultRelease Build1
    # ubuntu-16.10
    - stage: Build (1st run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-6 LINUX=ubuntu-16.10
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/build.sh DefaultDebug Build1
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (1st run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultRelease COMPILER=gcc-6 LINUX=ubuntu-16.10
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/build.sh DefaultRelease Build1
      before_cache:
        docker cp storm:/storm/. .
    # debian-9
    - stage: Build (1st run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-6 LINUX=debian-9
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/build.sh DefaultDebug Build1
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (1st run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultRelease COMPILER=gcc-6 LINUX=debian-9
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/build.sh DefaultRelease Build1
      before_cache:
        docker cp storm:/storm/. .

    ###
    # Stage: Build (2nd run)
    ###

    # osx
    - stage: Build (2nd run)
      os: osx
      compiler: clang
      env: BUILD=DefaultDebug COMPILER=clang-4.0 STL=libc++
      install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/build.sh DefaultDebug Build2
    - stage: Build (2nd run)
      os: osx
      compiler: clang
      env: BUILD=DefaultRelease COMPILER=clang-4.0 STL=libc++
      install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/build.sh DefaultRelease Build2
    # ubuntu-16.10
    - stage: Build (2nd run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-6 LINUX=ubuntu-16.10
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/build.sh DefaultDebug Build2
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (2nd run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultRelease COMPILER=gcc-6 LINUX=ubuntu-16.10
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/build.sh DefaultRelease Build2
      before_cache:
        docker cp storm:/storm/. .
    # debian-9
    - stage: Build (2nd run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-6 LINUX=debian-9
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/build.sh DefaultDebug Build2
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (2nd run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultRelease COMPILER=gcc-6 LINUX=debian-9
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/build.sh DefaultRelease Build2
      before_cache:
        docker cp storm:/storm/. .

    ###
    # Stage: Build (3rd run)
    ###

    # osx
    - stage: Build (3rd run)
      os: osx
      compiler: clang
      env: BUILD=DefaultDebug COMPILER=clang-4.0 STL=libc++
      install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/build.sh DefaultDebug Build3
    - stage: Build (3rd run)
      os: osx
      compiler: clang
      env: BUILD=DefaultRelease COMPILER=clang-4.0 STL=libc++
      install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/build.sh DefaultRelease Build3
    # ubuntu-16.10
    - stage: Build (3rd run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-6 LINUX=ubuntu-16.10
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/build.sh DefaultDebug Build3
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (3rd run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultRelease COMPILER=gcc-6 LINUX=ubuntu-16.10
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/build.sh DefaultRelease Build3
      before_cache:
        docker cp storm:/storm/. .
    # debian-9
    - stage: Build (3rd run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-6 LINUX=debian-9
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/build.sh DefaultDebug Build3
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (3rd run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultRelease COMPILER=gcc-6 LINUX=debian-9
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/build.sh DefaultRelease Build3
      before_cache:
        docker cp storm:/storm/. .

    ###
    # Stage: Build (4th run)
    ###

    # osx
    - stage: Build (4th run)
      os: osx
      compiler: clang
      env: BUILD=DefaultDebug COMPILER=clang-4.0 STL=libc++
      install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/build.sh DefaultDebug Build4
    - stage: Build (4th run)
      os: osx
      compiler: clang
      env: BUILD=DefaultRelease COMPILER=clang-4.0 STL=libc++
      install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/build.sh DefaultRelease Build4
    # ubuntu-16.10
    - stage: Build (4th run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-6 LINUX=ubuntu-16.10
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/build.sh DefaultDebug Build4
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (4th run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultRelease COMPILER=gcc-6 LINUX=ubuntu-16.10
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/build.sh DefaultRelease Build4
      before_cache:
        docker cp storm:/storm/. .
    # debian-9
    - stage: Build (4th run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-6 LINUX=debian-9
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/build.sh DefaultDebug Build4
      before_cache:
        docker cp storm:/storm/. .
    - stage: Build (4th run)
      os: linux
      compiler: gcc
      env: BUILD=DefaultRelease COMPILER=gcc-6 LINUX=debian-9
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/build.sh DefaultRelease Build4
      before_cache:
        docker cp storm:/storm/. .

    ###
    # Stage: Test all
    ###

    # osx
    - stage: Test all
      os: osx
      compiler: clang
      env: BUILD=DefaultDebug COMPILER=clang-4.0 STL=libc++
      install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/build.sh DefaultDebug TestAll
    - stage: Test all
      os: osx
      compiler: clang
      env: BUILD=DefaultRelease COMPILER=clang-4.0 STL=libc++
      install: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/install_osx.sh
      script: export OS=osx; export COMPILER='clang-4.0'; export STL='libc++';
        travis/build.sh DefaultRelease TestAll
    # ubuntu-16.10
    - stage: Test all
      os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-6 LINUX=ubuntu-16.10
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/build.sh DefaultDebug TestAll
      before_cache:
        docker cp storm:/storm/. .
    - stage: Test all
      os: linux
      compiler: gcc
      env: BUILD=DefaultRelease COMPILER=gcc-6 LINUX=ubuntu-16.10
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='ubuntu-16.10';
        travis/build.sh DefaultRelease TestAll
      before_cache:
        docker cp storm:/storm/. .
    # debian-9
    - stage: Test all
      os: linux
      compiler: gcc
      env: BUILD=DefaultDebug COMPILER=gcc-6 LINUX=debian-9
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/build.sh DefaultDebug TestAll
      before_cache:
        docker cp storm:/storm/. .
    - stage: Test all
      os: linux
      compiler: gcc
      env: BUILD=DefaultRelease COMPILER=gcc-6 LINUX=debian-9
      install: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/install_linux.sh
      script: export OS=linux; export COMPILER='gcc-6'; export LINUX='debian-9';
        travis/build.sh DefaultRelease TestAll
      before_cache:
        docker cp storm:/storm/. .

