name: apply-code-format

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: './src'
        clangFormatVersion: 12
        style: file
        inplace: True
    - uses: EndBug/add-and-commit@v4
      with:
        author_name: Auto Format
        author_email: dev@stormchecker.org
        message: 'Applied automatic code formating.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
